Connect4 project
Danielewin8/Springboard pull request #11
Opened 2022-11-13 19:03 UTC by Danielewin8

2022-11-15 04:01 UTC, rfair404 requested changes

2022-11-15 04:01 UTC, rfair404 commented on 10.7MapsAndSetsExercise/app.js
> +
@Danielewin8 Can you clean up this file, removing the numeric comments, and extra line breaks?

2022-11-15 04:01 UTC, rfair404 commented on 10.7MapsAndSetsExercise/app.js
> +  function vowelCount(str){
It would be a good idea to clean up the formatting (indentation). Functions, and their closing braces, should all be at the same level of indentation. There are tools that integrate with vscode for this (check out eslint).

2022-11-15 04:01 UTC, rfair404 commented on Connect4Project/app.js
> +   // TODO: set "board" to empty HEIGHT x WIDTH matrix array
if you complete the TODO's good idea to remove the comments. Or better yet, re-write them explaining your code.

2022-11-15 04:01 UTC, rfair404 commented on Connect4Project/app.js
> +   }
This especially could use a comment, just explain what all of the conditions are.

2022-11-15 04:01 UTC, rfair404 commented on Connect4Project/app.js
> +     }
Do you understand this code? Can you explain it in comments? it's confusing to me. There are more elegant ways to do this, but if it works, then you're good.

2022-11-15 04:04 UTC, rfair404 commented on 10.7MapsAndSetsExercise/app.js
> +
@Danielewin8 it also looks like there is some cross-contamination from other projects in this branch.

2022-11-16 04:59 UTC, Danielewin8 commented on 10.7MapsAndSetsExercise/app.js
> +
@rfair404 Yes I am not sure as to how the cross-contamination is happening or how to fix it. Its effecting new branches i make too..

2022-11-16 05:46 UTC, rfair404 commented
It is because you're basing your new branches off the previous branch.
When you do git checkout, the new branch is based off the current branch.
So next time checkout the main branch (git checkout main), then checkout
the new branch (git checkout -b). This will base it off main instead. It's
probably a good idea also to pull main (git pull origin main), before
creating the new branch,  since there are changes now merged.

On Tue, Nov 15, 2022, 21:59 Daniel Lewin ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In 10.7MapsAndSetsExercise/app.js
> <https://github.com/Danielewin8/Springboard/pull/11#discussion_r1023505002>
> :
>
> > +// 1.
> +
>
> @rfair404 <https://github.com/rfair404> Yes I am not sure as to how the
> cross-contamination is happening or how to fix it. Its effecting new
> branches i make too..
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Danielewin8/Springboard/pull/11#discussion_r1023505002>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFOM3STKB7C7UQYH2SPUGDWIRS3JANCNFSM6AAAAAAR7FEQP4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-16 19:14 UTC, merged